# Generated by Django 4.2.1 on 2023-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicestart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStartSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_content', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('btn_name', models.CharField(max_length=200)),
                ('btn_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='AboutStart/images/')),
                ('skills', models.ManyToManyField(to='home.aboutstartskills')),
            ],
        ),
    ]
