# Generated by Django 5.0 on 2023-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutstartskills_aboutstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='TestimonialItems/images/')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_content', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(to='home.testimonialitem')),
            ],
        ),
    ]
